### ISSUE TITLE
Post-release - back merge from the default branch into develop

### ISSUE THREAD

**Issue by CHarnel** [hoangvvo/gitflow-workflow-action#24]
Currently it is merging from `release/*` branch into `develop`. If we merge from the default (`main`) branch into `develop`, the `release/*` branch can be auto-deleted on PR closing, and also the `develop` branch wouldn't get "behind" master.

**Comment by hoangvvo** [comment]
I understand the reasoning about branch not being "behind", but I am not sure about merging from `main` back to `develop`. Do we have any resources that point out this direction? Most of the articles I found online instruct us to merge from the `feature` branch back to `develop`.

**Comment by CHarnel** [comment]
One reference I know is a tool called [fork](https://git-fork.com/) - when you work with GitFlow there, and finish a release, the release branch will be merged into main, tagged, and then back-merged from main to develop.
